name: PotPvP
version: 1.0
author: Hylist Games & Shiva Team
main: net.frozenorb.potpvp.PotPvPSI
depend: [ ShivaLib , ProtocolLib , WorldEdit ]
softdepend: [ Core ]
commands:
    p invite:
    team invite **:
    f leave:
    editpotion modify:
    dem:
    halp:
    party pass:
    arena listarenas:
    f create:
    party ffa:
    team devffa:
    team leader:
    p create:
    t create:
    team open:
    team kick:
    night:
    f info:
    accept:
    t inv:
    party invite:
    ?:
    silentfollow:
    tstatus:
    party disband:
    party kick:
    f unlock:
    party open:
    _:
    preferences:
    silent:
    f:
    team leave:
    toggleduels:
    team:
    1v1:
    td:
    p:
    p leave:
    team disband:
    t:
    t invite:
    t invite **:
    tournament join:
    invite:
    p inv:
    tournament cancel:
    team unlock:
    f invite **:
    f leader:
    t help:
    f devffa:
    ui:
    leave:
    t password:
    f inv:
    team info:
    f lock:
    uv:
    djm:
    f join:
    p devffa:
    t join:
    t lock:
    match status:
    p i:
    f help:
    t inv **:
    party:
    inv **:
    unfollow:
    party info:
    party inv:
    party create:
    t unlock:
    nightmode:
    team i:
    t disband:
    duel:
    p pass:
    rmqread:
    kit loaddefault:
    rmqimport:
    p kick:
    t leader:
    prefs:
    p open:
    manage:
    p teamsplit:
    updatevisibility:
    upvisflicker:
    upvis:
    f disband:
    leader:
    t leave:
    team lock:
    tournament start:
    invite **:
    team join:
    party leave:
    party i:
    checkpostmatchinv:
    options:
    arena createschematic:
    join:
    elo setteam:
    tcancel:
    suicide:
    party invite **:
    tduels:
    team ffa:
    party help:
    team help:
    f i:
    togglematches unranked:
    recalcglobalelo:
    party join:
    tournament status:
    eloconvert:
    f inv **:
    spectate:
    t info:
    party lock:
    status:
    ping:
    f ffa:
    updatevisibilityflicker:
    updateinventory:
    p info:
    f password:
    f teamsplit:
    party devffa:
    updateinv:
    t teamsplit:
    map:
    arena listschematics:
    updatevis:
    kill:
    arena free:
    help:
    p password:
    team teamsplit:
    arena scale:
    t ffa:
    team password:
    team create:
    party unlock:
    spec:
    team invite:
    f pass:
    t kick:
    kit wipekits player:
    host:
    togglematches ranked:
    kit savedefault:
    t open:
    settings:
    t devffa:
    helpme:
    forceend:
    p disband:
    kit wipekits type:
    match list:
    party password:
    elo setsolo:
    rmqset:
    t i:
    f open:
    p inv **:
    f kick:
    p unlock:
    p join:
    p ffa:
    p lock:
    arena repasteschematic:
    upinv:
    t pass:
    party leader:
    updatevisflicker:
    p help:
    uvf:
    pstatus:
    party teamsplit:
    p leader:
    tournament forcestart:
    p invite **:
    follow:
    inv:
    f invite:
    spawn:
    party inv **:
    build:
    team pass:
    jointournament: